name: smart_medical_box_app
description: A Smart Medical Box application for medication management and health monitoring.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  fl_chart: ^0.65.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  flutter_local_notifications: ^19.1.0
  google_sign_in: ^6.1.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
dependency_overrides:
  flutter_local_notifications_linux:
    git:
      url: https://github.com/MaikuB/flutter_local_notifications.git
      path: flutter_local_notifications_linux
